### ISSUE TITLE
Create Service Layer for Product Entity

### ISSUE THREAD

**Issue by l3002** [l3002/bgm-web-app#11]
### Task Description

Related to #8 

Create initial Service Layer for Product Entity and add a few methods to it.

### Task List

- [ ] Create Product Service
- [ ] Add a few methods to Product Service

### Acceptance Criteria

- [ ] Completion of the above task list.
