### ISSUE TITLE
Add Service Layer Implementation for Category

### ISSUE THREAD

**Issue by l3002** [l3002/bgm-web-app#13]
### Task Description

Related to #8 

Implement Service Layer for Category and add Business Logic to it.

### Task List

- [ ] Create `CategoryService` in `service` package
- [ ] Add a few methods to it. 

### Acceptance Criteria

- [ ] Completion of the task list
