### ISSUE TITLE
Create `repository` package for Repositories

### ISSUE THREAD

**Issue by l3002** [l3002/bgm-web-app#15]
### Task Description

The Repositories created for the data reside in the `data` package right now. Create a new package `repository` to `com.bgm.webapp` and add move all the repositories in it.

### Task List

- [ ] Create a new package `com.bgm.webapp.repository`
- [ ] Add all the repositories to the above created package

### Acceptance Criteria

- [ ] Achieve all the tasks in the task list.
