### ISSUE TITLE
Add Service Layer for `User` Class

### ISSUE THREAD

**Issue by l3002** [l3002/bgm-web-app#17]
### Task Description

Related to #8 

`UserRepository` is directly being used by existing Services and Controllers. Add a User Service Layer for business logic associated with `User`.

### Task List

- [ ] Create `UserService`
- [ ] Add useful methods to `UserService`
- [ ] Replace any direct use of `UserRepository` with `UserService`

### Acceptance Criteria

- [ ] Achieve all the tasks in the task list
