### ISSUE TITLE
Define REST Controllers for Product

### ISSUE THREAD

**Issue by l3002** [l3002/bgm-web-app#2]
### Task Description

Backend needs REST API to communicate with React frontend. Create REST Controllers for Product to handle API Calls.

### Task List

- [ ] Create REST Controller for Product
- [ ] Define Request Handlers for specific API Calls

> NOTE : Use Specific Request Annotations rather than using RequestMapping Annotation for all the handlers.

### Acceptance Criteria

- [ ] Complete all the tasks mentioned in the task list
- [ ] Test all the request handlers accordingly in the local environment
