### ISSUE TITLE
Create Home Page for the Application

### ISSUE THREAD

**Issue by l3002** [l3002/bgm-web-app#7]
### Task Description

Create a simple homepage for application. Design simple layout and specific components for main page.

Take reference from any online business website for relevant sections of the page.

### Task List

- [ ] Configure Project with React
- [ ] Add HTML, CSS and JS for the homepage
- [ ] Define homepage according to clients requirements
- [ ] Create logical division of page for specific parts
- [ ] Add Relevant data about the company

### Acceptance Criteria

- [ ] Completes the Whole Task List
- [ ] Define a basic homepage with links to other pages.
