### ISSUE TITLE
Add Service Layer Implementation

### ISSUE THREAD

**Issue by l3002** [l3002/bgm-web-app#8]
### Task Description

The Backend doesn't have a Service Layer. Adding Service Layer is essential for using dependency injections for their full potential and creating a flexible application.

### Task List

- [ ] Create a package for Business Logic
- [ ] Define Business logic for specific data objects

### Acceptance Criteria

- [ ] Complete all the tasks mentioned in the task list above
